[book]
authors = ["Nicolas Rodriguez"]
language = "en"
src = "src"
title = "Learning copper-rs"

[build]
build-dir = "output"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/NRdrgz/copper-rs-book"
site-url = "/copper-rs-book/"
additional-css = ["theme/brand.css"]
